spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:8889/butjet3?serverTimezone=Europe/Moscow
    username: butjet
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
server:
  port: 8008
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#springfox:
#  documentation:
#    swagger-ui:
#      base-url: /api/swagger/
#    org.springframework.boot.autoconfigure: DEBUG